const DUMMY_DATA = [
  {
    id: 0,
    cdRank: 1,
    collegeLogo: "",
    collegeName:
      "IIT-Madras - Indian Institute of Technology - [IITM], Chennai",
    address: "Chennai, Tamil Nadu",
    approvedBy: "AICTE",
    jeeCutoff: 144,
    courseFees: "2,09,550",
    userReviewRating: "8.6",
    totalUserReviews: "289",
    ranking: "3rd/131",
    isFeatured: true,
    placement: { averagePackage: "21,48,000", highestPackage: "1,98,00,000" },
  },
  {
    id: 1,
    cdRank: 2,
    collegeLogo: "",
    collegeName:
      "IIT-Delhi - Indian Institute of Technology - [IITD], New Delhi",
    address: "New Delhi, Delhi NCR",
    approvedBy: "",
    jeeCutoff: 115,
    courseFees: "2,54,650",
    userReviewRating: "8.7",
    totalUserReviews: "485",
    ranking: "1st/35",
    isFeatured: true,
    placement: { averagePackage: "25,82,000", highestPackage: "2,00,00,000" },
  },
  {
    id: 2,
    cdRank: 3,
    collegeLogo: "",
    collegeName: "Parul University, Vadodara",
    address: "Vadodara, Gujarat",
    approvedBy: "AICTE, COA, PCI, INC, GNC",
    jeeCutoff: "",
    courseFees: "1,49,000",
    userReviewRating: "8.1",
    totalUserReviews: "802",
    ranking: "99/147",
    isFeatured: true,
    placement: { averagePackage: "4,00,000", highestPackage: "30,00,000" },
  },
  {
    id: 3,
    cdRank: 4,
    collegeLogo: "",
    collegeName: "IIT Bombay - Indian Institute of Technology - [IITB], Mumbai",
    address: "Mumbai, Maharashtra",
    approvedBy: "AICTE, UGC",
    jeeCutoff: 66,
    courseFees: "2,29,300",
    userReviewRating: "8.8",
    totalUserReviews: "306",
    ranking: "2nd/35",
    isFeatured: true,
    placement: { averagePackage: "21,82,000", highestPackage: "3,67,00,000" },
  },
];

export default DUMMY_DATA;
